### ISSUE TITLE
tonlib-opencl-cli: Check `lite_client` failed (tonlib-cuda-cli works)

### ISSUE THREAD

**Issue by alexander-n-lunev** [tontechio/pow-miner-gpu#112]
Hello! I'm trying to use pow-miner-gpu, build process ends without errors. But when I run tonlib-opencl-cli I get error (below). tonlib-cuda-cli works (I have no nvidia cards, so it just tell me that no cards found). 
At first I tried to build with opencl libraries from repository, then I tried to build with OpenCL-SDK from Khronos (but I really don't know what opencl libraries is using build process). 

/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli -v -C ~/global.config.json -e 'pminer start auto $wallet_address 0 32'
```
[ 0][t 1][2021-12-05 17:24:23.703580294][tonlib-cli.cpp:1092][!console]	Check `lite_client` failed
[pid 23467] [time 1638725063] Signal: 6
------- Stack Backtrace -------
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x2490b1)[0x55c8ebf8d0b1]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x2493b1)[0x55c8ebf8d3b1]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x246298)[0x55c8ebf8a298]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12980)[0x7f81b991f980]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f81b8a13fb7]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f81b8a15921]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x268c27)[0x55c8ebfacc27]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x271d25)[0x55c8ebfb5d25]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x268aba)[0x55c8ebfacaba]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x25b8de)[0x55c8ebf9f8de]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(_ZZN9TonlibCli14run_pminer_cmdERN2td6detail10ParserImplINS0_5SliceEEENS0_7PromiseINS0_4UnitEEEENUlNS0_6ResultIS7_EEE_clESA_+0x1df)[0x55c8ebe3472f]
[ 0][t 2][2021-12-05 17:24:23.704558244][tonlib-cli.cpp:837][!PowMiner]	Check `lite_client` failed
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(_ZN2td13LambdaPromiseINS_4UnitEZN9TonlibCli14run_pminer_cmdERNS_6detail10ParserImplINS_5SliceEEENS_7PromiseIS1_EEEUlNS_6ResultIS1_EEE_E9set_errorEONS_6StatusE+0x3c)[0x55c8ebe34a2c]
[pid 23467] [time 1638725063] Signal: 6
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli------- Stack Backtrace -------
(_ZN2td7PromiseINS_4UnitEE9set_errorEONS_6StatusE+0x1a)[0x55c8ebe2ec9a]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x2490b1)[0x55c8ebf8d0b1]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(_ZZN9TonlibCli23check_liteserver_syncedEdN2td7PromiseINS0_4UnitEEEENUlOT_E_clINS0_6ResultISt10unique_ptrIN3ton10tonlib_api15liteServer_infoESt14default_deleteISC_EEEEEEDaS5_+0x7a)[0x55c8ebe52c3a]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x2493b1)[0x55c8ebf8d3b1]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(_ZN2td13LambdaPromiseISt10unique_ptrIN3ton10tonlib_api15liteServer_infoESt14default_deleteIS4_EEZN9TonlibCli23check_liteserver_syncedEdNS_7PromiseINS_4UnitEEEEUlOT_E_E9set_errorEONS_6StatusE+0x46)[0x55c8ebe5feb6]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x246298)[0x55c8ebf8a298]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(_ZZN9TonlibCli10send_queryIN3ton10tonlib_api18liteServer_getInfoEEEvSt10unique_ptrIT_St14default_deleteIS5_EEN2td7PromiseINS5_10ReturnTypeEEEENUlNS9_6ResultIS4_INS2_6ObjectES6_ISE_EEEEE_clESH_+0x40)[0x/lib/x86_64-linux-gnu/libpthread.so.055c8ebe41410(]
+0x12980)[0x7f81b991f980]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(_ZN2td13LambdaPromiseISt10unique_ptrIN3ton10tonlib_api6ObjectESt14default_deleteIS4_EEZN9TonlibCli10send_queryINS3_18liteServer_getInfoEEEvS1_IT_S5_ISB_EENS_7PromiseINSB_10ReturnTypeEEEEUlNS_6ResultIS7_EEE_E9set_errorEONS_6StatusE+0x3b)[0x55c8ebe5769b]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f81b8a13fb7]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(_ZN9TonlibCli15on_tonlib_errorEmSt10unique_ptrIN3ton10tonlib_api5errorESt14default_deleteIS3_EE+0x103)[0x55c8ebe2a913]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f81b8a15921]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(_ZN2td5actor6detail18ActorMessageLambdaIZNS1_23send_closure_later_implINS_14DelayedClosureI9TonlibCliMS5_FvmSt10unique_ptrIN3ton10tonlib_api5errorESt14default_deleteIS9_EEEJRmOSC_EEEEEvNS1_8ActorRefEOT_EUlvE_E3runEv+0x53)[0x55c8ebe47893]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x268c27)[0x55c8ebfacc27]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x22532a)[0x55c8ebf6932a]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x271d25)[0x55c8ebfb5d25]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x22558d)[0x55c8ebf6958d]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x268aba)[0x55c8ebfacaba]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x234806)[0x55c8ebf78806]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x25b8de)[0x55c8ebf9f8de]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x228c5d)[0x55c8ebf6cc5d]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(_ZN9TonlibCli8PowMiner15with_giver_infoEN2td6ResultISt10unique_ptrIN3ton10tonlib_api13smc_runResultESt14default_deleteIS6_EEEE+0x22f)[0x55c8ebe43e8f]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(_ZN2td6detail13ThreadPthread10run_threadEPv+0x37)[0x55c8ebe27347]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(_ZN9TonlibCli8PowMiner16with_giver_stateEN2td6ResultISt10unique_ptrIN3ton10tonlib_api8smc_infoESt14default_deleteIS6_EEEE+0x73)[0x55c8ebe8a3e3/lib/x86_64-linux-gnu/libpthread.so.0]
(+0x76db)[0x7f81b99146db]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(_ZN2td5actor6detail18ActorMessageLambdaIZNS1_23send_closure_later_implINS_14DelayedClosureIN9TonlibCli8PowMinerEMS6_FvNS_6ResultISt10unique_ptrIN3ton10tonlib_api8smc_infoESt14default_deleteISB_EEEEEJOSF_EEEEEvNS1_8ActorRefEOT_EUlvE_E3runEv+0x57)[0x55c8ebe4f8b7]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f81b8af671f]
-------------------------------
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x22532a)[0x55c8ebf6932a]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x22558d)[0x55c8ebf6958d]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x234806)[0x55c8ebf78806]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(+0x228c5d)[0x55c8ebf6cc5d]
/usr/bin/ton-opencl/tonlib/tonlib-opencl-cli(_ZN2td6detail13ThreadPthread10run_threadEPv+0x37)[0x55c8ebe27347]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f81b99146db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f81b8af671f]
-------------------------------
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
/home/lan/23467: No such file or directory.
No thread selected
[New LWP 23468]
[New LWP 23469]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f81b8af6a47 in epoll_wait (epfd=4, events=0x55c8ed4a7250, maxevents=1000, timeout=10000) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
30	../sysdeps/unix/sysv/linux/epoll_wait.c: No such file or directory.
[Current thread is 1 (Thread 0x7f81ba86fc40 (LWP 23467))]

Thread 3 (Thread 0x7f81b7ca4700 (LWP 23469)):
#0  0x00007f81b991f32a in __waitpid (pid=23471, stat_loc=0x0, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
        resultvar = 18446744073709551104
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x000055c8ebf8d2f6 in td::(anonymous namespace)::print_backtrace_gdb() ()
No symbol table info available.
#2  0x000055c8ebf8a298 in td::default_failure_signal_handler(int) ()
No symbol table info available.
#3  <signal handler called>
No locals.
#4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {0, 140195140854716, 140195110990640, 5, 5, 140195110990384, 2, 94321440715349, 94321446415272, 140195110990416, 0, 51, 140195157038080, 1638725063704558244, 29, 140195140796248}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#5  0x00007f81b8a15921 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 140192027508744, 15783376766943560960, 140195138647712}}, sa_flags = 0, sa_restorer = 0x63}
        sigs = {__val = {32, 0 <repeats 15 times>}}
        __cnt = <optimized out>
        __set = <optimized out>
        __cnt = <optimized out>
        __set = <optimized out>
#6  0x000055c8ebfacc27 in td::process_fatal_error(td::CSlice) ()
No symbol table info available.
#7  0x000055c8ebfb5d25 in td::DefaultLog::append(td::CSlice, int) ()
No symbol table info available.
#8  0x000055c8ebfacaba in td::Logger::~Logger() ()
No symbol table info available.
#9  0x000055c8ebf9f8de in td::detail::process_check_error(char const*, char const*, int) ()
No symbol table info available.
#10 0x000055c8ebe43e8f in TonlibCli::PowMiner::with_giver_info(td::Result<std::unique_ptr<ton::tonlib_api::smc_runResult, std::default_delete<ton::tonlib_api::smc_runResult> > >) ()
No symbol table info available.
#11 0x000055c8ebe8a3e3 in TonlibCli::PowMiner::with_giver_state(td::Result<std::unique_ptr<ton::tonlib_api::smc_info, std::default_delete<ton::tonlib_api::smc_info> > >) ()
No symbol table info available.
#12 0x000055c8ebe4f8b7 in td::actor::detail::ActorMessageLambda<void td::actor::detail::send_closure_later_impl<td::DelayedClosure<TonlibCli::PowMiner, void (TonlibCli::PowMiner::*)(td::Result<std::unique_ptr<ton::tonlib_api::smc_info, std::default_delete<ton::tonlib_api::smc_info> > >), td::Result<std::unique_ptr<ton::tonlib_api::smc_info, std::default_delete<ton::tonlib_api::smc_info> > >&&> >(td::actor::detail::ActorRef, td::DelayedClosure<TonlibCli::PowMiner, void (TonlibCli::PowMiner::*)(td::Result<std::unique_ptr<ton::tonlib_api::smc_info, std::default_delete<ton::tonlib_api::smc_info> > >), td::Result<std::unique_ptr<ton::tonlib_api::smc_info, std::default_delete<ton::tonlib_api::smc_info> > >&&>&&)::{lambda()#1}>::run() ()
No symbol table info available.
#13 0x000055c8ebf6932a in td::actor::core::ActorExecutor::flush_one_message() ()
No symbol table info available.
#14 0x000055c8ebf6958d in td::actor::core::ActorExecutor::start() ()
No symbol table info available.
#15 0x000055c8ebf78806 in td::actor::core::CpuWorker::run() ()
No symbol table info available.
#16 0x000055c8ebf6cc5d in td::LambdaDestructor<td::detail::ThreadPthread::ThreadPthread<td::actor::core::Scheduler::start()::{lambda()#1}>(td::actor::core::Scheduler::start()::{lambda()#1}&&)::{lambda()#1}>::~LambdaDestructor() ()
No symbol table info available.
#17 0x000055c8ebe27347 in td::detail::ThreadPthread::run_thread(void*) ()
No symbol table info available.
#18 0x00007f81b99146db in start_thread (arg=0x7f81b7ca4700) at pthread_create.c:463
        pd = 0x7f81b7ca4700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140195110995712, -7893650558319675363, 140195110993664, 0, 94321462814848, 140725140923520, 7887897756735027229, 7887893674104633373}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#19 0x00007f81b8af671f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7f81b85a6700 (LWP 23468)):
#0  0x00007f81b991f32a in __waitpid (pid=23470, stat_loc=0x0, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
        resultvar = 18446744073709551104
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x000055c8ebf8d2f6 in td::(anonymous namespace)::print_backtrace_gdb() ()
No symbol table info available.
#2  0x000055c8ebf8a298 in td::default_failure_signal_handler(int) ()
No symbol table info available.
#3  <signal handler called>
No locals.
#4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {0, 140195140854716, 140195120435328, 5, 5, 140195120435536, 2, 94321440715349, 94321446415272, 140195120435568, 0, 51, 140194980333936, 15783376766943560960, 29, 140194980320240}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#5  0x00007f81b8a15921 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 140192027508744, 15783376766943560960, 140195138647712}}, sa_flags = 0, sa_restorer = 0x63}
        sigs = {__val = {32, 0 <repeats 15 times>}}
        __cnt = <optimized out>
        __set = <optimized out>
        __cnt = <optimized out>
        __set = <optimized out>
#6  0x000055c8ebfacc27 in td::process_fatal_error(td::CSlice) ()
No symbol table info available.
#7  0x000055c8ebfb5d25 in td::DefaultLog::append(td::CSlice, int) ()
No symbol table info available.
#8  0x000055c8ebfacaba in td::Logger::~Logger() ()
No symbol table info available.
#9  0x000055c8ebf9f8de in td::detail::process_check_error(char const*, char const*, int) ()
No symbol table info available.
#10 0x000055c8ebe3472f in TonlibCli::run_pminer_cmd(td::detail::ParserImpl<td::Slice>&, td::Promise<td::Unit>)::{lambda(td::Result<td::Unit>)#1}::operator()(td::Result<td::Unit>) ()
No symbol table info available.
#11 0x000055c8ebe34a2c in td::LambdaPromise<td::Unit, TonlibCli::run_pminer_cmd(td::detail::ParserImpl<td::Slice>&, td::Promise<td::Unit>)::{lambda(td::Result<td::Unit>)#1}>::set_error(td::Status&&) ()
No symbol table info available.
#12 0x000055c8ebe2ec9a in td::Promise<td::Unit>::set_error(td::Status&&) ()
No symbol table info available.
#13 0x000055c8ebe52c3a in TonlibCli::check_liteserver_synced(double, td::Promise<td::Unit>)::{lambda(auto:1&&)#1}::operator()<td::Result<std::unique_ptr<ton::tonlib_api::liteServer_info, std::default_delete<ton::tonlib_api> > > > ()
No symbol table info available.
#14 0x000055c8ebe5feb6 in td::LambdaPromise<std::unique_ptr<ton::tonlib_api::liteServer_info, std::default_delete<ton::tonlib_api::liteServer_info> >, TonlibCli::check_liteserver_synced(double, td::Promise<td::Unit>)::{lambda(auto:1&&)#1}>::set_error(td::Status&&) ()
No symbol table info available.
#15 0x000055c8ebe41410 in void TonlibCli::send_query<ton::tonlib_api::liteServer_getInfo>(std::unique_ptr<ton::tonlib_api::liteServer_getInfo, std::default_delete<ton::tonlib_api::liteServer_getInfo> >, td::Promise<ton::tonlib_api::liteServer_getInfo::ReturnType>)::{lambda(td::Result<std::unique_ptr<ton::tonlib_api::Object, std::default_delete<ton::tonlib_api::Object> > >)#1}::operator()(td::Result<std::unique_ptr<ton::tonlib_api::Object, std::default_delete<ton::tonlib_api::Object> > >) ()
No symbol table info available.
#16 0x000055c8ebe5769b in td::LambdaPromise<std::unique_ptr<ton::tonlib_api::Object, std::default_delete<ton::tonlib_api::Object> >, void TonlibCli::send_query<ton::tonlib_api::liteServer_getInfo>(std::unique_ptr<ton::tonlib_api::liteServer_getInfo, std::default_delete<ton::tonlib_api::liteServer_getInfo> >, td::Promise<ton::tonlib_api::liteServer_getInfo::ReturnType>)::{lambda(td::Result<std::unique_ptr<ton::tonlib_api::Object, std::default_delete<ton::tonlib_api::Object> > >)#1}>::set_error(td::Status&&) ()
No symbol table info available.
#17 0x000055c8ebe2a913 in TonlibCli::on_tonlib_error(unsigned long, std::unique_ptr<ton::tonlib_api::error, std::default_delete<ton::tonlib_api::error> >) ()
No symbol table info available.
#18 0x000055c8ebe47893 in td::actor::detail::ActorMessageLambda<void td::actor::detail::send_closure_later_impl<td::DelayedClosure<TonlibCli, void (TonlibCli::*)(unsigned long, std::unique_ptr<ton::tonlib_api::error, std::default_delete<ton::tonlib_api::error> >), unsigned long&, std::unique_ptr<ton::tonlib_api::error, std::default_delete<ton::tonlib_api::error> >&&> >(td::actor::detail::ActorRef, td::DelayedClosure<TonlibCli, void (TonlibCli::*)(unsigned long, std::unique_ptr<ton::tonlib_api::error, std::default_delete<ton::tonlib_api::error> >), unsigned long&, std::unique_ptr<ton::tonlib_api::error, std::default_delete<ton::tonlib_api::error> >&&>&&)::{lambda()#1}>::run() ()
No symbol table info available.
#19 0x000055c8ebf6932a in td::actor::core::ActorExecutor::flush_one_message() ()
No symbol table info available.
#20 0x000055c8ebf6958d in td::actor::core::ActorExecutor::start() ()
No symbol table info available.
#21 0x000055c8ebf78806 in td::actor::core::CpuWorker::run() ()
No symbol table info available.
#22 0x000055c8ebf6cc5d in td::LambdaDestructor<td::detail::ThreadPthread::ThreadPthread<td::actor::core::Scheduler::start()::{lambda()#1}>(td::actor::core::Scheduler::start()::{lambda()#1}&&)::{lambda()#1}>::~LambdaDestructor() ()
No symbol table info available.
#23 0x000055c8ebe27347 in td::detail::ThreadPthread::run_thread(void*) ()
No symbol table info available.
#24 0x00007f81b99146db in start_thread (arg=0x7f81b85a6700) at pthread_create.c:463
        pd = 0x7f81b85a6700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140195120441088, -7893650558319675363, 140195120439040, 0, 94321462813648, 140725140923520, 7887894317539964957, 7887893674104633373}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#25 0x00007f81b8af671f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7f81ba86fc40 (LWP 23467)):
#0  0x00007f81b8af6a47 in epoll_wait (epfd=4, events=0x55c8ed4a7250, maxevents=1000, timeout=10000) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
        resultvar = 18446744073709551612
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x000055c8ebf9960e in td::detail::Epoll::run(int) ()
No symbol table info available.
#2  0x000055c8ebf7bff2 in td::actor::core::IoWorker::run_once(double, bool) ()
No symbol table info available.
#3  0x000055c8ebf6d1d0 in td::actor::core::Scheduler::run(double) ()
No symbol table info available.
#4  0x000055c8ebe20d8b in main ()
No symbol table info available.
```

**Comment by DelphiR** [comment]
This problem is reproduced only with CUDA build and only for Kepler GPU chips.
These nvidia kepler is deprecated and not supported.
